import { z } from 'zod';

export const updateSettingsSchema = z.object({
  organizationName: z.string().min(1, 'Organization name is required').optional(),
  companyName: z.string().optional().nullable(),
  industry: z.string().optional().nullable(),
  website: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  phone: z.string().optional().nullable(),
  timeZone: z.string().optional().nullable(),
  address: z.string().optional().nullable(),
  logoUrl: z.string().optional().nullable(),
  primaryColor: z.string().optional().nullable(),
  accentColor: z.string().optional().nullable(),
  applicationName: z.string().optional().nullable(),
  passwordMinLength: z.number().int().min(8, 'Minimum length is 8').max(32, 'Maximum length is 32').optional(),
  requireUppercase: z.boolean().optional(),
  requireNumbers: z.boolean().optional(),
  requireSymbols: z.boolean().optional(),
  sessionTimeoutMinutes: z.number().int().min(5, 'Minimum timeout is 5 minutes').max(1440, 'Maximum timeout is 1440 minutes').optional(),
  mfaEnabled: z.boolean().optional(),
  emailNotifications: z.boolean().optional(),
  browserNotifications: z.boolean().optional(),
  criticalAlerts: z.boolean().optional(),
  dailySummaryEmails: z.boolean().optional(),
  theme: z.enum(['dark', 'light', 'system']).optional(),
  sidebarCollapsed: z.boolean().optional(),
  compactMode: z.boolean().optional(),
});
