import { z } from 'zod';

export const updateSettingsSchema = z.object({
  organizationName: z.string().min(1, 'Organization name is required'),
  companyName: z.string().optional().nullable().default(null),
  industry: z.string().optional().nullable().default(null),
  website: z.string().url('Invalid website URL').optional().nullable().or(z.literal('')).default(null),
  email: z.string().email('Invalid email format').optional().nullable().or(z.literal('')).default(null),
  phone: z.string().optional().nullable().default(null),
  timeZone: z.string().optional().nullable().default(null),
  address: z.string().optional().nullable().default(null),
  logoUrl: z.string().optional().nullable().default(null),
  primaryColor: z.string().optional().nullable().default(null),
  accentColor: z.string().optional().nullable().default(null),
  applicationName: z.string().optional().nullable().default(null),
  passwordMinLength: z.number().int().min(8, 'Minimum length is 8').max(32, 'Maximum length is 32').default(12),
  requireUppercase: z.boolean().default(true),
  requireNumbers: z.boolean().default(true),
  requireSymbols: z.boolean().default(true),
  sessionTimeoutMinutes: z.number().int().min(5, 'Minimum timeout is 5 minutes').max(1440, 'Maximum timeout is 1440 minutes').default(60),
  mfaEnabled: z.boolean().default(false),
  emailNotifications: z.boolean().default(true),
  browserNotifications: z.boolean().default(true),
  criticalAlerts: z.boolean().default(true),
  dailySummaryEmails: z.boolean().default(false),
  theme: z.enum(['dark', 'light', 'system']).default('system'),
  sidebarCollapsed: z.boolean().default(false),
  compactMode: z.boolean().default(false),
});